In [1]:
import os
# import string
import numpy as np
import pandas as pd
# import networkx as nx
from pathlib import Path
from tqdm import tqdm, trange
# import re
# import json
# import pickle

import torch
import torchmetrics
import lightning.pytorch as pl
# from torch.utils.data import Dataset, random_split, DataLoader

from src.utils.misc_utils import load_sharded_dataset, print_time_slices
from src.utils.plotting_utils import plot_lagged_adjacency_structure

import warnings
warnings.filterwarnings("ignore")

roc = torchmetrics.classification.BinaryROC()
auroc = torchmetrics.classification.BinaryAUROC()

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

### Data Permutations

##### Permute train & val splits

In [ ]:
from src.utils.misc_utils import load_sharded_dataset, print_time_slices
# from scipy.stats import ks_2samp
# import matplotlib.pyplot as plt
# import seaborn as sns
# import string
import random

""" Path """
cpd_path = Path("data/mix_100k_pt")
split = "train"
destination_path = Path("data/mix_100k_p3_pt")

""" Data """
data_iterator = load_sharded_dataset(base_path=cpd_path, split=split)

# for j, data in enumerate(data_iterator): 
#     print(len(data))

data = next(data_iterator)
print(len(data))

In [ ]:
from src.utils.misc_utils import load_sharded_dataset, print_time_slices
# from scipy.stats import ks_2samp
# import matplotlib.pyplot as plt
# import seaborn as sns
# import string
import random

""" Path """
cpd_path = Path("data/mix_100k_pt")
split = "test"
destination_path = Path("data/mix_100k_p3_pt")

""" Data """
data_iterator = load_sharded_dataset(base_path=cpd_path, split=split)

for j, data in enumerate(data_iterator): 

    # hyperparameters
    num_permutations = 3

    permuted_data = []
    for pair in [random.choice(data) for _ in range(int(len(data)/4))]:
        permuted_data.append(pair)
        datum = pair[0]
        graph = pair[1]
        datum = datum[:500, :] # trimming the simulated data
        graph = torch.Tensor(graph) # trimming the simulated data
        padded_feats = []
        # sanity checks
        if datum.shape!=torch.Size([500, 12]):
            print(f"Warning: datum.shape={datum.shape}")
        if graph.shape!=torch.Size([12, 12, 3]):
            print(f"Warning: graph.shape={graph.shape}")
        if type(graph)!=torch.Tensor:
            print(f"Warning: graph.type={type(graph)}")
        # identify padded features based on mean (padded ones follow a distribution with a singinficantly smaller mean)
        min_mean = np.min([np.mean(datum.numpy()[:, i]) for i in range(datum.shape[1])])
        mean_interval = pd.Interval(left=min_mean-np.abs(min_mean/2), right=min_mean+np.abs(min_mean/2))
        feats = np.arange(datum.shape[1])
        for i in feats:
            if np.mean(datum.numpy()[:, i]) in mean_interval:
                padded_feats.append(i)
        # permute features at random for both data & graph (assuming the identification of padded features works correctly - seems so)
        for _ in range(num_permutations):
            if padded_feats!=[]:
                permuted_feats = np.concat([
                    np.random.permutation(feats[:min(padded_feats)]), 
                    feats[min(padded_feats):]
                ])
            else:
                permuted_feats = np.random.permutation(feats)
            permuted_datum = datum.clone()[:, permuted_feats]
            permuted_graph = graph.clone()[permuted_feats, :, :][:, permuted_feats, :]
            permuted_data.append([permuted_datum, permuted_graph])

    np.random.shuffle(permuted_data)
    destination_folder = destination_path / split
    os.makedirs(destination_folder, exist_ok=True)
    torch.save(permuted_data, destination_folder / f"{split}_shard{j}.pt")

##### Permute test split into separate groups for each pair (to measure variability of predictions)

In [ ]:
""" Path """
cpd_path = Path("data/mix_100k_pt")
split = "test"
destination_path = Path("data/mix_400k_p3_pt")

destination_split = "testvar"
destination_folder = destination_path / destination_split
os.makedirs(destination_folder, exist_ok=True)

""" Data """
data_iterator = load_sharded_dataset(base_path=cpd_path, split=split)

for j, data in enumerate(data_iterator): 

    # hyperparameters
    num_permutations = 9

    for k, pair in enumerate(data[:]):
        permuted_data = []
        datum = pair[0]
        graph = pair[1]
        datum = datum[:500, :] # trimming the simulated data
        graph = torch.Tensor(graph) # convert all graph types to torch tensor
        permuted_data.append([datum, graph])
        padded_feats = []
        # sanity checks
        if datum.shape!=torch.Size([500, 12]):
            print(f"Warning: datum.shape={datum.shape}")
        if graph.shape!=torch.Size([12, 12, 3]):
            print(f"Warning: graph.shape={graph.shape}")
        if type(graph)!=torch.Tensor:
            print(f"Warning: graph.type={type(graph)}")
        # identify padded features based on mean (padded ones follow a distribution with a singinficantly smaller mean)
        min_mean = np.min([np.mean(datum.numpy()[:, i]) for i in range(datum.shape[1])])
        mean_interval = pd.Interval(left=min_mean-np.abs(min_mean/2), right=min_mean+np.abs(min_mean/2))
        feats = np.arange(datum.shape[1])
        for i in feats:
            if np.mean(datum.numpy()[:, i]) in mean_interval:
                padded_feats.append(i)
        # permute features at random for both data & graph (assuming the identification of padded features works correctly - seems so)
        for _ in range(num_permutations):
            if padded_feats!=[]:
                permuted_feats = np.concat([
                    np.random.permutation(feats[:min(padded_feats)]), 
                    feats[min(padded_feats):]
                ])
            else:
                permuted_feats = np.random.permutation(feats)
            permuted_datum = datum.clone()[:, permuted_feats]
            permuted_graph = graph.clone()[permuted_feats, :, :][:, permuted_feats, :]
            permuted_data.append([permuted_datum, permuted_graph])

        torch.save(permuted_data, destination_folder / f"{destination_split}_shard{j}_{k}.pt")

### Models

In [2]:
from src.modules.informer_module import InformerModule

# Paths
par_dir = Path(os.getcwd())
out_path = Path(par_dir / "outputs")

# try:
#     out_path.mkdir(parents=True, exist_ok=False)
#     print(f"Created: {out_path}")
# except FileExistsError:
#     print(f"{out_path} already exists.")


models = {
    "LCM_CI_plain_100k_2c5M_20E_01_27": InformerModule.load_from_checkpoint(checkpoint_path=Path("logs/plain_100k_2c5M_20E_01_27/last.ckpt")), 
    "LCM_CI_perm_100k_2c5M_20E_01_28": InformerModule.load_from_checkpoint(checkpoint_path=Path("logs/perm_100k_2c5M_20E_01_28/last.ckpt")),
    "LCM_CI_perm_100k_2c5M_20E_01_31": InformerModule.load_from_checkpoint(checkpoint_path=Path("logs/perm_100k_2c5M_20E_01_31/last.ckpt")),
    "LCM_CI_perm_400k_2c5M_3E_01_29": InformerModule.load_from_checkpoint(checkpoint_path=Path("logs/perm_400k_2c5M_3E_01_29/last.ckpt")),
}

### Test Inference

In [ ]:
from src.utils.utils import lagged_batch_crosscorrelation
from src.utils.misc_utils import print_time_slices

data = pd.DataFrame(np.random.rand(500, 12))

X_cpd = torch.tensor(data.values, device='cuda', dtype=torch.float32)

model_name, model = list(models.items())[-1]

model.eval()
if (X_cpd.shape[0]>500):
    X_cpd = X_cpd[:500]
pred = torch.sigmoid(model((X_cpd.unsqueeze(0), lagged_batch_crosscorrelation(X_cpd.unsqueeze(0), 3)))[0])

pred[pred<=0.05] = 0
pred[pred>0.05] = 1

print_time_slices(pred)

In [ ]:
import string
from src.utils.utils import lagged_batch_crosscorrelation, _from_cp_to_full
from src.utils.transformation_utils import _edges_for_causal_stationarity, regular_order_pd, group_lagged_nodes


def estimate_with_LCM(
        true_data: pd.DataFrame,
        model: str,
        thresholded: bool=True,
        threshold: float=0.05,
        enforce_density: bool=False,
        density: list=[2, 10]
) -> tuple: 
    """
    Wrapper for calling LCM models for causal discovery.
    Models used are extended to a maximum of 12 variables a 3 lags, trained on a mixture of synthetic and realistic data. 

    Args
    ----
    data_pd (pd.DataFrame) : a dataframe containing the true time-series data
    model (str) : the path to the PyTorch Lightning model checkpoint
                            trained for up 12 variables and 3 lags, using Correlation Injection (CI) 
    thresholded (bool) : whether to threshold the predicted values or not, in order to have a binary output (default : `True`)
    threshold (floa) : the threshold value used, if thresholded is true (default : `0.05`)
    
    Returns
    ------- 
    (adj_cp, adj_pd) (tuple) : the lagged adjacency matrix (torch.Tensor), together with the full-time graph representation (pandas.DataFrame)

    Notes
    -----
    ...
    """
    true_data.rename(columns=dict(zip(data.columns, list(string.ascii_uppercase)[:len(list(data.columns))])), inplace=True)

    if isinstance(density, list):
        density = np.random.choice(range(density[0], density[1]))

    # Model preparation
    M = InformerModule.load_from_checkpoint(Path(model))
    M = M.to("cpu")
    M = M.eval()
    
    # Data convertion
    data_pd = true_data.copy()
    X_data = torch.tensor(data_pd.values, device='cpu', dtype=torch.float32)

    # Normalization
    X_data = (X_data - X_data.min()) / (X_data.max() - X_data.min())

    # Padding
    MAX_VAR = 12
    VAR_DIF = MAX_VAR - X_data.shape[1]
    if X_data.shape[1] != MAX_VAR:
        X_data = torch.concat(
            [X_data, torch.normal(0, 0.01, (X_data.shape[0], VAR_DIF))], axis=1
        )

    # Check dimensions and decide whether batched approach is needed
    if (X_data.shape[0]>500):
        # bs_preds = []
        # batches = [X_data[500*icr: 500*(icr+1), :] for icr in range(X_data.shape[0]//500)]
        # if 500*(X_data.shape[0]//500) < X_data.shape[0]:
        #     batches.append(X_data[500*(X_data.shape[0]//500):, :])

        # bs_preds = [torch.sigmoid(model((bs.unsqueeze(0), lagged_batch_crosscorrelation(bs.unsqueeze(0), 3)))[0]) for bs in batches]
        # preds = torch.cat(bs_preds, dim=0)
        # pred = preds.mean(0).unsqueeze(0)
        X_data = X_data[:500]
        pred = torch.sigmoid(M((X_data.unsqueeze(0), lagged_batch_crosscorrelation(X_data.unsqueeze(0), 3)))[0])

    else:
        pred = torch.sigmoid(M((X_data.unsqueeze(0), lagged_batch_crosscorrelation(X_data.unsqueeze(0), 3)))[0])

    # Threshold values if a binary output is required
    if thresholded:

        if enforce_density:
            threshold_search_space = np.linspace(5e-7, 0.9, 50)
            dist_to_avg = {}
            for thr in threshold_search_space:
                pred_c = pred[0].detach().numpy().copy()
                pred_c[pred_c < thr] = 0
                pred_c[pred_c >= thr] = 1
                dist_to_avg[thr] = abs(density - pred_c.sum().astype(int))

            dist_to_avg = {k: v for k, v in sorted(dist_to_avg.items(), key=lambda item: item[1])}
            threshold = list(dist_to_avg.keys())[0]

        pred[pred < threshold] = 0
        pred[pred >= threshold] = 1

    adj_cp = pred.detach().numpy()
    # print_time_slices(adj_cp)
    adj_pd = _from_cp_to_full(adj_cp=adj_cp)
    adj_pd = _edges_for_causal_stationarity(temp_adj_pd=adj_pd)

    # __________ Post-processing __________ 
    adj_pd = adj_pd.loc[regular_order_pd(adj_pd=adj_pd), regular_order_pd(adj_pd=adj_pd)]
    adj_pd = adj_pd.loc[
        [col for col in adj_pd.columns if col.split("_t")[0] in data_pd.columns], 
        [col for col in adj_pd.columns if col.split("_t")[0] in data_pd.columns]
    ]
    nodes_to_retain = adj_pd.columns.to_list()
    groups = group_lagged_nodes(adj_pd.columns)
    for key in list(reversed([x for x in groups.keys() if x!="0"])):
        if adj_pd.loc[groups[key], groups['0']].values.sum()==0:
            nodes_to_retain = [col for col in nodes_to_retain if col not in groups[key]]
        else:
            break   # to avoid having empty intermediate time slices
    adj_pd = adj_pd.loc[nodes_to_retain, nodes_to_retain]
    # adj_cp = _from_full_to_cp(adj_pd)

    return adj_cp, adj_pd

data = pd.DataFrame(np.random.rand(500, 5))

model_path = Path("logs/perm_100k_2c5M_20E_01_31/last.ckpt")
adj_cp, adj_pd = estimate_with_LCM(true_data=data, model=model_path)

adj_pd

,A_t,B_t,C_t,D_t,E_t,F_t,G_t,H_t,I_t,J_t,K_t,L_t,A_t-1,B_t-1,C_t-1,D_t-1,E_t-1,F_t-1,G_t-1,H_t-1,I_t-1,J_t-1,K_t-1,L_t-1,A_t-2,B_t-2,C_t-2,D_t-2,E_t-2,F_t-2,G_t-2,H_t-2,I_t-2,J_t-2,K_t-2,L_t-2,A_t-3,B_t-3,C_t-3,D_t-3,E_t-3,F_t-3,G_t-3,H_t-3,I_t-3,J_t-3,K_t-3,L_t-3
A_t,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
B_t,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
C_t,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
D_t,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
E_t,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
F_t,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
G_t,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
H_t,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
I_t,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
J_t,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
K_t,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
L_t,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
A_t-1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
B_t-1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
C_t-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
D_t-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
E_t-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
F_t-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
G_t-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
H_t-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
I_t-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
J_t-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
K_t-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
L_t-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
A_t-2,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
B_t-2,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
C_t-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
D_t-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
E_t-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
F_t-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
G_t-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
H_t-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
I_t-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
J_t-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
K_t-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
L_t-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
A_t-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
B_t-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
C_t-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
D_t-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
E_t-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
F_t-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
G_t-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
H_t-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
I_t-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
J_t-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
K_t-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
L_t-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

### Test Sharded

In [ ]:
from src.utils.misc_utils import load_sharded_dataset, print_time_slices
from src.utils.utils import lagged_batch_crosscorrelation
from src.utils.metrics import custom_binary_metrics

""" Path """
cpd_path = Path("data/synth_230k_sim_45k_pt/test")

""" Placeholders """
results_df = pd.DataFrame(columns=["model", "AUC", "TPR", "FPR", "TNR", "FNR"])
results_dict = {}


""" Data """
data_iterator = load_sharded_dataset(base_path=Path("data/synth_230k_sim_45k_pt"), split="test")
data = next(data_iterator)

""" Model loop """
for model_name, model in zip(models.keys(), models.values()):

    print(f"\n___{model_name}___")
    model.eval()

    prc_list = []
    tpr_list = [] 
    fpr_list = []
    tnr_list = []
    fnr_list = []
    auc_list = []
    
    for pair in tqdm(data[:]):

        X_cpd = pd.DataFrame(data=pair[0]) 
        Y_cpd = pair[1] 

#         if "PCMCI" in model_name: 
#             pred = run_inv_pcmci(X_cpd, c_test=None, max_tau=Y_cpd.shape[2], invert=False)

#         elif model_name == "PCMCI+":
#             pred = run_inv_pcmciplus(X_cpd, c_test=None, max_tau=Y_cpd.shape[2], invert=False)
        
#         elif "DYNOTEARS" in model_name:
#             pred_pd = run_dynotears(data=X_cpd, n_lags=Y_cpd.shape[2])
#             pred = _from_full_to_cp(pred_pd)
        
        if "_deep_" or "_lcm_" or "LCM_" in model_name:
            X_cpd = torch.tensor(X_cpd.values, device='cuda', dtype=torch.float32)

            if (X_cpd.shape[0]>500):
                X_cpd = X_cpd[:500]
                if ("LCM" in model_name):
                    pred = torch.sigmoid(model((X_cpd.unsqueeze(0), lagged_batch_crosscorrelation(X_cpd.unsqueeze(0), 3)))[0])
                else:
                    pred = torch.sigmoid(model((X_cpd.unsqueeze(0), lagged_batch_crosscorrelation(X_cpd.unsqueeze(0), 3))))
                pred = pred.unsqueeze(0)

            else:
                if ("LCM" in model_name):    
                    with torch.no_grad():
                        pred = torch.sigmoid(model((X_cpd.unsqueeze(0), lagged_batch_crosscorrelation(X_cpd.unsqueeze(0), 3))))
                else:
                    with torch.no_grad():
                        pred = torch.sigmoid(model(X_cpd.unsqueeze(0)))
            pred = pred[0]


        else:
            continue

        if Y_cpd.sum()<=0 or Y_cpd.sum()==np.prod(Y_cpd.shape):
            continue  

        # prc, tpr, fpr, tnr, fnr, auc = custom_binary_metrics(binary=pred.clone(), A=Y_cpd.clone(), verbose=False, precision=True)
        tpr, fpr, tnr, fnr, auc = custom_binary_metrics(binary=pred.clone(), A=Y_cpd, verbose=False)

        auc_list.append(float(auc))
        # prc_list.append(float(prc))
        tpr_list.append(float(tpr)) 
        fpr_list.append(float(fpr))
        tnr_list.append(float(tnr))
        fnr_list.append(float(fnr))

    results_dict[model_name] = [token for token in auc_list]
    results_df.loc[len(results_df), :] = [model_name, np.array(auc_list).mean(), np.array(tpr_list).mean(), np.array(fpr_list).mean(), 
                        np.array(tnr_list).mean(), np.array(fnr_list).mean()]

results_df[['model', 'AUC', 'TPR', 'FPR', 'TNR', 'FNR']]

### Test Variance

In [10]:
from src.utils.misc_utils import load_sharded_dataset, print_time_slices
from src.utils.utils import lagged_batch_crosscorrelation
from src.utils.metrics import custom_binary_metrics, SHD

""" Placeholders """
total_var_df = pd.DataFrame(
    columns=["auc_var", "shd_var"], 
    index=[model_name for model_name, _ in list(zip(models.keys(), models.values()))[:]],
    data=np.zeros(shape=[len(list(zip(models.keys(), models.values()))[:]), 2])
)

""" Data """
data_iterator = load_sharded_dataset(base_path=Path("data/mix_400k_p3_pt"), split="testvar")
dum_list = []

NUM_GROUPS = 300
SUB = 0
for _ in trange(NUM_GROUPS):
    data = next(data_iterator)

    """ Placeholders """
    var_df = pd.DataFrame(
        columns=["auc_var", "shd_var"], 
        index=[model_name for model_name, _ in list(zip(models.keys(), models.values()))[:]],
    )

    """ Model loop """
    # for model_name, model in zip(models.keys(), models.values()):
    for model_name, model in list(zip(models.keys(), models.values()))[:]:

        # print(f"\n___{model_name}___")
        model.eval()

        tpr_list = [] 
        fpr_list = []
        tnr_list = []
        fnr_list = []
        auc_list = []
        shd_list = []
        
        for pair in tqdm(data[:], disable=True):

            X_cpd = pd.DataFrame(data=pair[0]) 
            Y_cpd = torch.Tensor(pair[1]) 
            
            if "_deep_" or "_lcm_" or "LCM_" in model_name:
                X_cpd = torch.tensor(X_cpd.values, device='cuda', dtype=torch.float32)

                if (X_cpd.shape[0]>500):
                    X_cpd = X_cpd[:500]
                    if ("LCM" in model_name):
                        pred = torch.sigmoid(model((X_cpd.unsqueeze(0), lagged_batch_crosscorrelation(X_cpd.unsqueeze(0), 3)))[0])
                    else:
                        pred = torch.sigmoid(model((X_cpd.unsqueeze(0), lagged_batch_crosscorrelation(X_cpd.unsqueeze(0), 3))))
                    pred = pred.unsqueeze(0)

                else:
                    if ("LCM" in model_name):    
                        with torch.no_grad():
                            pred = torch.sigmoid(model((X_cpd.unsqueeze(0), lagged_batch_crosscorrelation(X_cpd.unsqueeze(0), 3))))
                    else:
                        with torch.no_grad():
                            pred = torch.sigmoid(model(X_cpd.unsqueeze(0)))
                pred = pred[0]


            else:
                continue

            if Y_cpd.sum()<=0 or Y_cpd.sum()==np.prod(Y_cpd.shape):
                continue  

            tpr, fpr, tnr, fnr, auc = custom_binary_metrics(binary=pred.clone(), A=Y_cpd, verbose=False)
            
            
            """ 
            - SHD requires integer adjacency matrices to be computed. 
            - Thresholding the predicted adjacency matrix can be tricky. 
            - Idea: use a threshold such that the number of predicted edges is the same as in the ground truth 
            """
            Y_cpd[Y_cpd < 0.05] = 0
            Y_cpd[Y_cpd >= 0.05] = 1
            density = Y_cpd.sum().item()
            threshold_search_space = np.linspace(5e-7, 0.9, 50)
            dist_to_avg = {}
            for thr in threshold_search_space:
                pred_c = pred.cpu().numpy().copy()
                pred_c[pred_c < thr] = 0
                pred_c[pred_c >= thr] = 1
                dist_to_avg[thr] = abs(density - pred_c.sum().astype(int))

            dist_to_avg = {k: v for k, v in sorted(dist_to_avg.items(), key=lambda item: item[1])}
            threshold = list(dist_to_avg.keys())[0]

            pred[pred < threshold] = 0
            pred[pred >= threshold] = 1

            ssd = SHD(target=Y_cpd, pred=pred)
            # print(f"    - SHD : {ssd}")

            auc_list.append(float(auc))
            tpr_list.append(float(tpr)) 
            fpr_list.append(float(fpr))
            tnr_list.append(float(tnr))
            fnr_list.append(float(fnr))
            shd_list.append(float(ssd))

        if auc_list==[]:
            continue
        var_df.loc[model_name, "auc_var"] = np.array(auc_list).var().round(4)
        var_df.loc[model_name, "shd_var"] = np.array(shd_list).var().round(4)

    # display(var_df)
    for col in total_var_df.columns:
        for ind in total_var_df.index:
            if var_df.loc[ind, col] is np.nan:
                SUB += 1
                break
            else:
                total_var_df.loc[ind, col] = total_var_df.loc[ind, col] + var_df.loc[ind, col]

tvd = (total_var_df / (NUM_GROUPS-SUB)).round(4)
display(tvd)

  0%|          | 0/300 [00:00<?, ?it/s]

- Found 2000 shard(s) for split 'testvar'
  ├── Loaded testvar_shard0_0.pt                 (10 datasamples)

  0%|          | 1/300 [00:00<02:16,  2.19it/s]

  ├── Loaded testvar_shard0_1.pt                 (10 datasamples)

  1%|          | 2/300 [00:00<02:20,  2.12it/s]

  ├── Loaded testvar_shard0_10.pt                (10 datasamples)

  1%|          | 3/300 [00:01<02:16,  2.17it/s]

  ├── Loaded testvar_shard0_100.pt               (10 datasamples)

  1%|▏         | 4/300 [00:01<02:10,  2.27it/s]

  ├── Loaded testvar_shard0_101.pt               (10 datasamples)

  2%|▏         | 5/300 [00:02<02:33,  1.92it/s]

  ├── Loaded testvar_shard0_102.pt               (10 datasamples)

  2%|▏         | 6/300 [00:03<02:42,  1.81it/s]

  ├── Loaded testvar_shard0_103.pt               (10 datasamples)

  2%|▏         | 7/300 [00:03<02:45,  1.77it/s]

  ├── Loaded testvar_shard0_104.pt               (10 datasamples)

  3%|▎         | 8/300 [00:04<02:42,  1.80it/s]

  ├── Loaded testvar_shard0_105.pt               (10 datasamples)

  3%|▎         | 9/300 [00:04<02:41,  1.80it/s]

  ├── Loaded testvar_shard0_106.pt               (10 datasamples)

  3%|▎         | 10/300 [00:05<02:41,  1.79it/s]

  ├── Loaded testvar_shard0_107.pt               (10 datasamples)

  4%|▎         | 11/300 [00:05<02:27,  1.95it/s]

  ├── Loaded testvar_shard0_108.pt               (10 datasamples)

  4%|▍         | 12/300 [00:06<02:29,  1.93it/s]

  ├── Loaded testvar_shard0_109.pt               (10 datasamples)

  4%|▍         | 13/300 [00:06<02:25,  1.98it/s]

  ├── Loaded testvar_shard0_11.pt                (10 datasamples)

  5%|▍         | 14/300 [00:07<02:19,  2.05it/s]

  ├── Loaded testvar_shard0_110.pt               (10 datasamples)

  5%|▌         | 15/300 [00:07<02:23,  1.99it/s]

  ├── Loaded testvar_shard0_111.pt               (10 datasamples)

  5%|▌         | 16/300 [00:08<02:44,  1.73it/s]

  ├── Loaded testvar_shard0_112.pt               (10 datasamples)

  6%|▌         | 17/300 [00:08<02:36,  1.81it/s]

  ├── Loaded testvar_shard0_113.pt               (10 datasamples)

  6%|▌         | 18/300 [00:09<02:32,  1.85it/s]

  ├── Loaded testvar_shard0_114.pt               (10 datasamples)

  6%|▋         | 19/300 [00:10<02:34,  1.82it/s]

  ├── Loaded testvar_shard0_115.pt               (10 datasamples)

  7%|▋         | 20/300 [00:10<02:28,  1.88it/s]

  ├── Loaded testvar_shard0_116.pt               (10 datasamples)

  7%|▋         | 21/300 [00:10<02:18,  2.01it/s]

  ├── Loaded testvar_shard0_117.pt               (10 datasamples)

  7%|▋         | 22/300 [00:11<02:15,  2.05it/s]

  ├── Loaded testvar_shard0_118.pt               (10 datasamples)

  8%|▊         | 23/300 [00:11<02:08,  2.15it/s]

  ├── Loaded testvar_shard0_119.pt               (10 datasamples)

  8%|▊         | 24/300 [00:12<02:06,  2.18it/s]

  ├── Loaded testvar_shard0_12.pt                (10 datasamples)

  8%|▊         | 25/300 [00:12<02:01,  2.26it/s]

  ├── Loaded testvar_shard0_120.pt               (10 datasamples)

  9%|▊         | 26/300 [00:13<02:07,  2.15it/s]

  ├── Loaded testvar_shard0_121.pt               (10 datasamples)

  9%|▉         | 27/300 [00:13<02:13,  2.05it/s]

  ├── Loaded testvar_shard0_122.pt               (10 datasamples)

  9%|▉         | 28/300 [00:14<02:13,  2.03it/s]

  ├── Loaded testvar_shard0_123.pt               (10 datasamples)

 10%|▉         | 29/300 [00:14<02:07,  2.12it/s]

  ├── Loaded testvar_shard0_124.pt               (10 datasamples)

 10%|█         | 30/300 [00:15<02:07,  2.11it/s]

  ├── Loaded testvar_shard0_125.pt               (10 datasamples)

 11%|█         | 32/300 [00:15<01:40,  2.66it/s]

  ├── Loaded testvar_shard0_126.pt               (10 datasamples)
  ├── Loaded testvar_shard0_127.pt               (10 datasamples)

 11%|█         | 33/300 [00:16<01:51,  2.40it/s]

  ├── Loaded testvar_shard0_128.pt               (10 datasamples)

 11%|█▏        | 34/300 [00:16<01:37,  2.72it/s]

  ├── Loaded testvar_shard0_129.pt               (10 datasamples)

 12%|█▏        | 35/300 [00:16<01:41,  2.62it/s]

  ├── Loaded testvar_shard0_13.pt                (10 datasamples)

 12%|█▏        | 36/300 [00:17<01:42,  2.57it/s]

  ├── Loaded testvar_shard0_130.pt               (10 datasamples)

 12%|█▏        | 37/300 [00:17<01:49,  2.40it/s]

  ├── Loaded testvar_shard0_131.pt               (10 datasamples)

 13%|█▎        | 38/300 [00:18<01:48,  2.41it/s]

  ├── Loaded testvar_shard0_132.pt               (10 datasamples)

 13%|█▎        | 39/300 [00:18<01:46,  2.45it/s]

  ├── Loaded testvar_shard0_133.pt               (10 datasamples)

 13%|█▎        | 40/300 [00:18<01:41,  2.55it/s]

  ├── Loaded testvar_shard0_134.pt               (10 datasamples)

 14%|█▎        | 41/300 [00:19<01:38,  2.64it/s]

  ├── Loaded testvar_shard0_135.pt               (10 datasamples)

 14%|█▍        | 42/300 [00:19<01:33,  2.75it/s]

  ├── Loaded testvar_shard0_136.pt               (10 datasamples)

 14%|█▍        | 43/300 [00:19<01:30,  2.84it/s]

  ├── Loaded testvar_shard0_137.pt               (10 datasamples)

 15%|█▍        | 44/300 [00:20<01:28,  2.88it/s]

  ├── Loaded testvar_shard0_138.pt               (10 datasamples)

 15%|█▌        | 45/300 [00:20<01:26,  2.96it/s]

  ├── Loaded testvar_shard0_139.pt               (10 datasamples)

 15%|█▌        | 46/300 [00:20<01:23,  3.03it/s]

  ├── Loaded testvar_shard0_14.pt                (10 datasamples)

 16%|█▌        | 47/300 [00:21<01:21,  3.09it/s]

  ├── Loaded testvar_shard0_140.pt               (10 datasamples)

 16%|█▋        | 49/300 [00:21<01:07,  3.72it/s]

  ├── Loaded testvar_shard0_141.pt               (10 datasamples)
  ├── Loaded testvar_shard0_142.pt               (10 datasamples)

 17%|█▋        | 50/300 [00:22<01:09,  3.59it/s]

  ├── Loaded testvar_shard0_143.pt               (10 datasamples)

 17%|█▋        | 51/300 [00:22<01:10,  3.51it/s]

  ├── Loaded testvar_shard0_144.pt               (10 datasamples)

 17%|█▋        | 52/300 [00:22<01:13,  3.39it/s]

  ├── Loaded testvar_shard0_145.pt               (10 datasamples)

 18%|█▊        | 54/300 [00:23<01:03,  3.85it/s]

  ├── Loaded testvar_shard0_146.pt               (10 datasamples)
  ├── Loaded testvar_shard0_147.pt               (10 datasamples)

 18%|█▊        | 55/300 [00:23<01:07,  3.65it/s]

  ├── Loaded testvar_shard0_148.pt               (10 datasamples)

 19%|█▊        | 56/300 [00:23<01:08,  3.54it/s]

  ├── Loaded testvar_shard0_149.pt               (10 datasamples)

 19%|█▉        | 57/300 [00:24<01:10,  3.46it/s]

  ├── Loaded testvar_shard0_15.pt                (10 datasamples)

 19%|█▉        | 58/300 [00:24<01:11,  3.37it/s]

  ├── Loaded testvar_shard0_150.pt               (10 datasamples)

 20%|█▉        | 59/300 [00:24<01:16,  3.13it/s]

  ├── Loaded testvar_shard0_151.pt               (10 datasamples)

 20%|██        | 60/300 [00:25<01:36,  2.48it/s]

  ├── Loaded testvar_shard0_152.pt               (10 datasamples)

 20%|██        | 61/300 [00:25<01:23,  2.87it/s]

  ├── Loaded testvar_shard0_153.pt               (10 datasamples)

 21%|██        | 62/300 [00:25<01:30,  2.62it/s]

  ├── Loaded testvar_shard0_154.pt               (10 datasamples)

 21%|██        | 63/300 [00:26<01:19,  2.96it/s]

  ├── Loaded testvar_shard0_155.pt               (10 datasamples)

 21%|██▏       | 64/300 [00:26<01:23,  2.82it/s]

  ├── Loaded testvar_shard0_156.pt               (10 datasamples)

 22%|██▏       | 65/300 [00:26<01:23,  2.82it/s]

  ├── Loaded testvar_shard0_157.pt               (10 datasamples)

 22%|██▏       | 66/300 [00:27<01:55,  2.03it/s]

  ├── Loaded testvar_shard0_158.pt               (10 datasamples)

 22%|██▏       | 67/300 [00:28<02:33,  1.52it/s]

  ├── Loaded testvar_shard0_159.pt               (10 datasamples)

 23%|██▎       | 68/300 [00:29<02:50,  1.36it/s]

  ├── Loaded testvar_shard0_16.pt                (10 datasamples)

 23%|██▎       | 69/300 [00:30<02:57,  1.30it/s]

  ├── Loaded testvar_shard0_160.pt               (10 datasamples)

 23%|██▎       | 70/300 [00:31<03:06,  1.24it/s]

  ├── Loaded testvar_shard0_161.pt               (10 datasamples)

 24%|██▎       | 71/300 [00:32<03:13,  1.18it/s]

  ├── Loaded testvar_shard0_162.pt               (10 datasamples)

 24%|██▍       | 72/300 [00:33<03:22,  1.12it/s]

  ├── Loaded testvar_shard0_163.pt               (10 datasamples)

 24%|██▍       | 73/300 [00:34<03:26,  1.10it/s]

  ├── Loaded testvar_shard0_164.pt               (10 datasamples)

 25%|██▍       | 74/300 [00:35<03:31,  1.07it/s]

  ├── Loaded testvar_shard0_165.pt               (10 datasamples)

 25%|██▌       | 75/300 [00:36<03:44,  1.00it/s]

  ├── Loaded testvar_shard0_166.pt               (10 datasamples)

 25%|██▌       | 76/300 [00:37<03:54,  1.05s/it]

  ├── Loaded testvar_shard0_167.pt               (10 datasamples)

 26%|██▌       | 77/300 [00:38<03:44,  1.01s/it]

  ├── Loaded testvar_shard0_168.pt               (10 datasamples)

 26%|██▌       | 78/300 [00:39<03:35,  1.03it/s]

  ├── Loaded testvar_shard0_169.pt               (10 datasamples)

 26%|██▋       | 79/300 [00:39<03:00,  1.23it/s]

  ├── Loaded testvar_shard0_17.pt                (10 datasamples)

 27%|██▋       | 80/300 [00:40<02:34,  1.43it/s]

  ├── Loaded testvar_shard0_170.pt               (10 datasamples)

 27%|██▋       | 81/300 [00:41<02:41,  1.35it/s]

  ├── Loaded testvar_shard0_171.pt               (10 datasamples)

 27%|██▋       | 82/300 [00:42<02:51,  1.27it/s]

  ├── Loaded testvar_shard0_172.pt               (10 datasamples)

 28%|██▊       | 83/300 [00:43<02:59,  1.21it/s]

  ├── Loaded testvar_shard0_173.pt               (10 datasamples)

 28%|██▊       | 84/300 [00:43<03:09,  1.14it/s]

  ├── Loaded testvar_shard0_174.pt               (10 datasamples)

 28%|██▊       | 85/300 [00:44<03:12,  1.12it/s]

  ├── Loaded testvar_shard0_175.pt               (10 datasamples)

 29%|██▊       | 86/300 [00:45<03:16,  1.09it/s]

  ├── Loaded testvar_shard0_176.pt               (10 datasamples)

 29%|██▉       | 87/300 [00:46<03:17,  1.08it/s]

  ├── Loaded testvar_shard0_177.pt               (10 datasamples)

 29%|██▉       | 88/300 [00:47<03:16,  1.08it/s]

  ├── Loaded testvar_shard0_178.pt               (10 datasamples)

 30%|██▉       | 89/300 [00:48<03:19,  1.06it/s]

  ├── Loaded testvar_shard0_179.pt               (10 datasamples)

 30%|███       | 90/300 [00:49<03:16,  1.07it/s]

  ├── Loaded testvar_shard0_18.pt                (10 datasamples)

 30%|███       | 91/300 [00:50<03:14,  1.07it/s]

  ├── Loaded testvar_shard0_180.pt               (10 datasamples)

 31%|███       | 92/300 [00:51<03:15,  1.07it/s]

  ├── Loaded testvar_shard0_181.pt               (10 datasamples)

 31%|███       | 93/300 [00:52<03:17,  1.05it/s]

  ├── Loaded testvar_shard0_182.pt               (10 datasamples)

 31%|███▏      | 94/300 [00:53<03:14,  1.06it/s]

  ├── Loaded testvar_shard0_183.pt               (10 datasamples)

 32%|███▏      | 95/300 [00:54<03:16,  1.04it/s]

  ├── Loaded testvar_shard0_184.pt               (10 datasamples)

 32%|███▏      | 96/300 [00:55<03:17,  1.03it/s]

  ├── Loaded testvar_shard0_185.pt               (10 datasamples)

 32%|███▏      | 97/300 [00:56<03:20,  1.01it/s]

  ├── Loaded testvar_shard0_186.pt               (10 datasamples)

 33%|███▎      | 98/300 [00:57<03:15,  1.03it/s]

  ├── Loaded testvar_shard0_187.pt               (10 datasamples)

 33%|███▎      | 99/300 [00:58<03:24,  1.02s/it]

  ├── Loaded testvar_shard0_188.pt               (10 datasamples)

 33%|███▎      | 100/300 [00:59<03:25,  1.03s/it]

  ├── Loaded testvar_shard0_189.pt               (10 datasamples)

 34%|███▎      | 101/300 [01:00<03:29,  1.05s/it]

  ├── Loaded testvar_shard0_19.pt                (10 datasamples)

 34%|███▍      | 102/300 [01:02<03:45,  1.14s/it]

  ├── Loaded testvar_shard0_190.pt               (10 datasamples)

 34%|███▍      | 103/300 [01:03<03:38,  1.11s/it]

  ├── Loaded testvar_shard0_191.pt               (10 datasamples)

 35%|███▍      | 104/300 [01:04<03:39,  1.12s/it]

  ├── Loaded testvar_shard0_192.pt               (10 datasamples)

 35%|███▌      | 105/300 [01:05<03:42,  1.14s/it]

  ├── Loaded testvar_shard0_193.pt               (10 datasamples)

 35%|███▌      | 106/300 [01:06<03:20,  1.03s/it]

  ├── Loaded testvar_shard0_194.pt               (10 datasamples)

 36%|███▌      | 107/300 [01:07<03:30,  1.09s/it]

  ├── Loaded testvar_shard0_195.pt               (10 datasamples)

 36%|███▌      | 108/300 [01:08<03:23,  1.06s/it]

  ├── Loaded testvar_shard0_196.pt               (10 datasamples)

 36%|███▋      | 109/300 [01:09<03:32,  1.11s/it]

  ├── Loaded testvar_shard0_197.pt               (10 datasamples)

 37%|███▋      | 110/300 [01:10<03:33,  1.12s/it]

  ├── Loaded testvar_shard0_198.pt               (10 datasamples)

 37%|███▋      | 111/300 [01:11<03:29,  1.11s/it]

  ├── Loaded testvar_shard0_199.pt               (10 datasamples)

 37%|███▋      | 112/300 [01:13<03:42,  1.18s/it]

  ├── Loaded testvar_shard0_2.pt                 (10 datasamples)

 38%|███▊      | 113/300 [01:14<03:46,  1.21s/it]

  ├── Loaded testvar_shard0_20.pt                (10 datasamples)

 38%|███▊      | 114/300 [01:15<03:39,  1.18s/it]

  ├── Loaded testvar_shard0_200.pt               (10 datasamples)

 38%|███▊      | 115/300 [01:16<03:10,  1.03s/it]

  ├── Loaded testvar_shard0_201.pt               (10 datasamples)

 39%|███▊      | 116/300 [01:17<03:10,  1.03s/it]

  ├── Loaded testvar_shard0_202.pt               (10 datasamples)

 39%|███▉      | 117/300 [01:18<03:14,  1.06s/it]

  ├── Loaded testvar_shard0_203.pt               (10 datasamples)

 39%|███▉      | 118/300 [01:19<03:20,  1.10s/it]

  ├── Loaded testvar_shard0_204.pt               (10 datasamples)

 40%|███▉      | 119/300 [01:20<03:22,  1.12s/it]

  ├── Loaded testvar_shard0_205.pt               (10 datasamples)

 40%|████      | 120/300 [01:21<03:22,  1.12s/it]

  ├── Loaded testvar_shard0_206.pt               (10 datasamples)

 40%|████      | 121/300 [01:23<03:23,  1.14s/it]

  ├── Loaded testvar_shard0_207.pt               (10 datasamples)

 41%|████      | 122/300 [01:23<02:52,  1.03it/s]

  ├── Loaded testvar_shard0_208.pt               (10 datasamples)

 41%|████      | 123/300 [01:24<02:59,  1.02s/it]

  ├── Loaded testvar_shard0_209.pt               (10 datasamples)

 41%|████▏     | 124/300 [01:25<02:58,  1.02s/it]

  ├── Loaded testvar_shard0_21.pt                (10 datasamples)

 42%|████▏     | 125/300 [01:26<03:04,  1.06s/it]

  ├── Loaded testvar_shard0_210.pt               (10 datasamples)

 42%|████▏     | 126/300 [01:28<03:08,  1.09s/it]

  ├── Loaded testvar_shard0_211.pt               (10 datasamples)

 42%|████▏     | 127/300 [01:29<03:05,  1.07s/it]

  ├── Loaded testvar_shard0_212.pt               (10 datasamples)

 43%|████▎     | 128/300 [01:30<03:03,  1.07s/it]

  ├── Loaded testvar_shard0_213.pt               (10 datasamples)

 43%|████▎     | 129/300 [01:31<03:01,  1.06s/it]

  ├── Loaded testvar_shard0_214.pt               (10 datasamples)

 43%|████▎     | 130/300 [01:32<02:57,  1.04s/it]

  ├── Loaded testvar_shard0_215.pt               (10 datasamples)

 44%|████▎     | 131/300 [01:33<03:04,  1.09s/it]

  ├── Loaded testvar_shard0_216.pt               (10 datasamples)

 44%|████▍     | 132/300 [01:34<03:08,  1.12s/it]

  ├── Loaded testvar_shard0_217.pt               (10 datasamples)

 44%|████▍     | 133/300 [01:35<03:02,  1.09s/it]

  ├── Loaded testvar_shard0_218.pt               (10 datasamples)

 45%|████▍     | 134/300 [01:36<02:58,  1.07s/it]

  ├── Loaded testvar_shard0_219.pt               (10 datasamples)

 45%|████▌     | 135/300 [01:37<02:56,  1.07s/it]

  ├── Loaded testvar_shard0_22.pt                (10 datasamples)

 45%|████▌     | 136/300 [01:38<02:54,  1.07s/it]

  ├── Loaded testvar_shard0_220.pt               (10 datasamples)

 46%|████▌     | 137/300 [01:39<02:30,  1.09it/s]

  ├── Loaded testvar_shard0_221.pt               (10 datasamples)

 46%|████▌     | 138/300 [01:40<02:33,  1.05it/s]

  ├── Loaded testvar_shard0_222.pt               (10 datasamples)

 46%|████▋     | 139/300 [01:41<02:33,  1.05it/s]

  ├── Loaded testvar_shard0_223.pt               (10 datasamples)

 47%|████▋     | 140/300 [01:42<02:42,  1.01s/it]

  ├── Loaded testvar_shard0_224.pt               (10 datasamples)

 47%|████▋     | 141/300 [01:43<02:24,  1.10it/s]

  ├── Loaded testvar_shard0_225.pt               (10 datasamples)

 47%|████▋     | 142/300 [01:44<02:36,  1.01it/s]

  ├── Loaded testvar_shard0_226.pt               (10 datasamples)

 48%|████▊     | 143/300 [01:45<02:36,  1.01it/s]

  ├── Loaded testvar_shard0_227.pt               (10 datasamples)

 48%|████▊     | 144/300 [01:46<02:45,  1.06s/it]

  ├── Loaded testvar_shard0_228.pt               (10 datasamples)

 48%|████▊     | 145/300 [01:47<02:45,  1.07s/it]

  ├── Loaded testvar_shard0_229.pt               (10 datasamples)

 49%|████▊     | 146/300 [01:48<02:46,  1.08s/it]

  ├── Loaded testvar_shard0_23.pt                (10 datasamples)

 49%|████▉     | 147/300 [01:49<02:44,  1.08s/it]

  ├── Loaded testvar_shard0_230.pt               (10 datasamples)

 49%|████▉     | 148/300 [01:50<02:37,  1.04s/it]

  ├── Loaded testvar_shard0_231.pt               (10 datasamples)

 50%|████▉     | 149/300 [01:51<02:32,  1.01s/it]

  ├── Loaded testvar_shard0_232.pt               (10 datasamples)

 50%|█████     | 150/300 [01:52<02:28,  1.01it/s]

  ├── Loaded testvar_shard0_233.pt               (10 datasamples)

 50%|█████     | 151/300 [01:53<02:24,  1.03it/s]

  ├── Loaded testvar_shard0_234.pt               (10 datasamples)

 51%|█████     | 152/300 [01:54<02:18,  1.07it/s]

  ├── Loaded testvar_shard0_235.pt               (10 datasamples)

 51%|█████     | 153/300 [01:55<02:13,  1.10it/s]

  ├── Loaded testvar_shard0_236.pt               (10 datasamples)

 51%|█████▏    | 154/300 [01:56<02:14,  1.09it/s]

  ├── Loaded testvar_shard0_237.pt               (10 datasamples)

 52%|█████▏    | 155/300 [01:57<02:18,  1.04it/s]

  ├── Loaded testvar_shard0_238.pt               (10 datasamples)

 52%|█████▏    | 156/300 [01:58<02:19,  1.03it/s]

  ├── Loaded testvar_shard0_239.pt               (10 datasamples)

 52%|█████▏    | 157/300 [01:59<02:18,  1.03it/s]

  ├── Loaded testvar_shard0_24.pt                (10 datasamples)

 53%|█████▎    | 158/300 [02:00<02:23,  1.01s/it]

  ├── Loaded testvar_shard0_240.pt               (10 datasamples)

 53%|█████▎    | 159/300 [02:01<02:23,  1.02s/it]

  ├── Loaded testvar_shard0_241.pt               (10 datasamples)

 53%|█████▎    | 160/300 [02:02<02:20,  1.00s/it]

  ├── Loaded testvar_shard0_242.pt               (10 datasamples)

 54%|█████▎    | 161/300 [02:03<02:19,  1.00s/it]

  ├── Loaded testvar_shard0_243.pt               (10 datasamples)

 54%|█████▍    | 162/300 [02:04<02:17,  1.00it/s]

  ├── Loaded testvar_shard0_244.pt               (10 datasamples)

 54%|█████▍    | 163/300 [02:05<02:18,  1.01s/it]

  ├── Loaded testvar_shard0_245.pt               (10 datasamples)

 55%|█████▍    | 164/300 [02:06<02:00,  1.13it/s]

  ├── Loaded testvar_shard0_246.pt               (10 datasamples)

 55%|█████▌    | 165/300 [02:06<02:01,  1.11it/s]

  ├── Loaded testvar_shard0_247.pt               (10 datasamples)

 55%|█████▌    | 166/300 [02:08<02:06,  1.06it/s]

  ├── Loaded testvar_shard0_248.pt               (10 datasamples)

 56%|█████▌    | 167/300 [02:09<02:09,  1.03it/s]

  ├── Loaded testvar_shard0_249.pt               (10 datasamples)

 56%|█████▌    | 168/300 [02:10<02:10,  1.01it/s]

  ├── Loaded testvar_shard0_25.pt                (10 datasamples)

 56%|█████▋    | 169/300 [02:11<02:14,  1.03s/it]

  ├── Loaded testvar_shard0_250.pt               (10 datasamples)

 57%|█████▋    | 170/300 [02:12<02:13,  1.03s/it]

  ├── Loaded testvar_shard0_251.pt               (10 datasamples)

 57%|█████▋    | 171/300 [02:13<02:12,  1.03s/it]

  ├── Loaded testvar_shard0_252.pt               (10 datasamples)

 57%|█████▋    | 172/300 [02:14<02:11,  1.03s/it]

  ├── Loaded testvar_shard0_253.pt               (10 datasamples)

 58%|█████▊    | 173/300 [02:15<02:10,  1.03s/it]

  ├── Loaded testvar_shard0_254.pt               (10 datasamples)

 58%|█████▊    | 174/300 [02:16<02:11,  1.04s/it]

  ├── Loaded testvar_shard0_255.pt               (10 datasamples)

 58%|█████▊    | 175/300 [02:17<02:08,  1.03s/it]

  ├── Loaded testvar_shard0_256.pt               (10 datasamples)

 59%|█████▊    | 176/300 [02:18<02:08,  1.04s/it]

  ├── Loaded testvar_shard0_257.pt               (10 datasamples)

 59%|█████▉    | 177/300 [02:19<02:11,  1.07s/it]

  ├── Loaded testvar_shard0_258.pt               (10 datasamples)

 59%|█████▉    | 178/300 [02:20<02:11,  1.08s/it]

  ├── Loaded testvar_shard0_259.pt               (10 datasamples)

 60%|█████▉    | 179/300 [02:21<02:13,  1.11s/it]

  ├── Loaded testvar_shard0_26.pt                (10 datasamples)

 60%|██████    | 180/300 [02:23<02:18,  1.15s/it]

  ├── Loaded testvar_shard0_260.pt               (10 datasamples)

 60%|██████    | 181/300 [02:24<02:19,  1.17s/it]

  ├── Loaded testvar_shard0_261.pt               (10 datasamples)

 61%|██████    | 182/300 [02:25<02:14,  1.14s/it]

  ├── Loaded testvar_shard0_262.pt               (10 datasamples)

 61%|██████    | 183/300 [02:26<02:14,  1.15s/it]

  ├── Loaded testvar_shard0_263.pt               (10 datasamples)

 61%|██████▏   | 184/300 [02:27<02:14,  1.16s/it]

  ├── Loaded testvar_shard0_264.pt               (10 datasamples)

 62%|██████▏   | 185/300 [02:28<02:10,  1.14s/it]

  ├── Loaded testvar_shard0_265.pt               (10 datasamples)

 62%|██████▏   | 186/300 [02:29<02:08,  1.12s/it]

  ├── Loaded testvar_shard0_266.pt               (10 datasamples)

 62%|██████▏   | 187/300 [02:31<02:10,  1.15s/it]

  ├── Loaded testvar_shard0_267.pt               (10 datasamples)

 63%|██████▎   | 188/300 [02:32<02:13,  1.19s/it]

  ├── Loaded testvar_shard0_268.pt               (10 datasamples)

 63%|██████▎   | 189/300 [02:33<02:11,  1.18s/it]

  ├── Loaded testvar_shard0_269.pt               (10 datasamples)

 63%|██████▎   | 190/300 [02:34<02:08,  1.17s/it]

  ├── Loaded testvar_shard0_27.pt                (10 datasamples)

 64%|██████▎   | 191/300 [02:35<02:07,  1.17s/it]

  ├── Loaded testvar_shard0_270.pt               (10 datasamples)

 64%|██████▍   | 192/300 [02:37<02:09,  1.20s/it]

  ├── Loaded testvar_shard0_271.pt               (10 datasamples)

 64%|██████▍   | 193/300 [02:38<02:07,  1.20s/it]

  ├── Loaded testvar_shard0_272.pt               (10 datasamples)

 65%|██████▍   | 194/300 [02:39<01:49,  1.04s/it]

  ├── Loaded testvar_shard0_273.pt               (10 datasamples)

 65%|██████▌   | 195/300 [02:40<01:52,  1.07s/it]

  ├── Loaded testvar_shard0_274.pt               (10 datasamples)

 65%|██████▌   | 196/300 [02:41<01:52,  1.08s/it]

  ├── Loaded testvar_shard0_275.pt               (10 datasamples)

 66%|██████▌   | 197/300 [02:42<01:51,  1.08s/it]

  ├── Loaded testvar_shard0_276.pt               (10 datasamples)

 66%|██████▌   | 198/300 [02:43<01:50,  1.09s/it]

  ├── Loaded testvar_shard0_277.pt               (10 datasamples)

 66%|██████▋   | 199/300 [02:44<01:53,  1.12s/it]

  ├── Loaded testvar_shard0_278.pt               (10 datasamples)

 67%|██████▋   | 200/300 [02:45<01:50,  1.10s/it]

  ├── Loaded testvar_shard0_279.pt               (10 datasamples)

 67%|██████▋   | 201/300 [02:46<01:47,  1.08s/it]

  ├── Loaded testvar_shard0_28.pt                (10 datasamples)

 67%|██████▋   | 202/300 [02:47<01:48,  1.11s/it]

  ├── Loaded testvar_shard0_280.pt               (10 datasamples)

 68%|██████▊   | 203/300 [02:48<01:43,  1.07s/it]

  ├── Loaded testvar_shard0_281.pt               (10 datasamples)

 68%|██████▊   | 204/300 [02:49<01:42,  1.06s/it]

  ├── Loaded testvar_shard0_282.pt               (10 datasamples)

 68%|██████▊   | 205/300 [02:50<01:37,  1.02s/it]

  ├── Loaded testvar_shard0_283.pt               (10 datasamples)

 69%|██████▊   | 206/300 [02:51<01:33,  1.01it/s]

  ├── Loaded testvar_shard0_284.pt               (10 datasamples)

 69%|██████▉   | 207/300 [02:52<01:30,  1.03it/s]

  ├── Loaded testvar_shard0_285.pt               (10 datasamples)

 69%|██████▉   | 208/300 [02:53<01:17,  1.19it/s]

  ├── Loaded testvar_shard0_286.pt               (10 datasamples)

 70%|██████▉   | 209/300 [02:54<01:20,  1.13it/s]

  ├── Loaded testvar_shard0_287.pt               (10 datasamples)

 70%|███████   | 210/300 [02:55<01:23,  1.08it/s]

  ├── Loaded testvar_shard0_288.pt               (10 datasamples)

 70%|███████   | 211/300 [02:56<01:22,  1.08it/s]

  ├── Loaded testvar_shard0_289.pt               (10 datasamples)

 71%|███████   | 212/300 [02:57<01:21,  1.07it/s]

  ├── Loaded testvar_shard0_29.pt                (10 datasamples)

 71%|███████   | 213/300 [02:57<01:18,  1.10it/s]

  ├── Loaded testvar_shard0_290.pt               (10 datasamples)

 71%|███████▏  | 214/300 [02:59<01:21,  1.05it/s]

  ├── Loaded testvar_shard0_291.pt               (10 datasamples)

 72%|███████▏  | 215/300 [03:00<01:32,  1.09s/it]

  ├── Loaded testvar_shard0_292.pt               (10 datasamples)

 72%|███████▏  | 216/300 [03:01<01:27,  1.04s/it]

  ├── Loaded testvar_shard0_293.pt               (10 datasamples)

 72%|███████▏  | 217/300 [03:02<01:22,  1.00it/s]

  ├── Loaded testvar_shard0_294.pt               (10 datasamples)

 73%|███████▎  | 218/300 [03:03<01:21,  1.01it/s]

  ├── Loaded testvar_shard0_295.pt               (10 datasamples)

 73%|███████▎  | 219/300 [03:04<01:20,  1.00it/s]

  ├── Loaded testvar_shard0_296.pt               (10 datasamples)

 73%|███████▎  | 220/300 [03:05<01:29,  1.12s/it]

  ├── Loaded testvar_shard0_297.pt               (10 datasamples)

 74%|███████▎  | 221/300 [03:06<01:32,  1.17s/it]

  ├── Loaded testvar_shard0_298.pt               (10 datasamples)

 74%|███████▍  | 222/300 [03:07<01:16,  1.02it/s]

  ├── Loaded testvar_shard0_299.pt               (10 datasamples)

 74%|███████▍  | 223/300 [03:08<01:17,  1.01s/it]

  ├── Loaded testvar_shard0_3.pt                 (10 datasamples)

 75%|███████▍  | 224/300 [03:09<01:19,  1.05s/it]

  ├── Loaded testvar_shard0_30.pt                (10 datasamples)

 75%|███████▌  | 225/300 [03:10<01:24,  1.12s/it]

  ├── Loaded testvar_shard0_300.pt               (10 datasamples)

 75%|███████▌  | 226/300 [03:12<01:27,  1.18s/it]

  ├── Loaded testvar_shard0_301.pt               (10 datasamples)

 76%|███████▌  | 227/300 [03:13<01:27,  1.20s/it]

  ├── Loaded testvar_shard0_302.pt               (10 datasamples)

 76%|███████▌  | 228/300 [03:14<01:27,  1.21s/it]

  ├── Loaded testvar_shard0_303.pt               (10 datasamples)

 76%|███████▋  | 229/300 [03:15<01:23,  1.18s/it]

  ├── Loaded testvar_shard0_304.pt               (10 datasamples)

 77%|███████▋  | 230/300 [03:16<01:21,  1.16s/it]

  ├── Loaded testvar_shard0_305.pt               (10 datasamples)

 77%|███████▋  | 231/300 [03:17<01:09,  1.01s/it]

  ├── Loaded testvar_shard0_306.pt               (10 datasamples)

 77%|███████▋  | 232/300 [03:18<01:07,  1.01it/s]

  ├── Loaded testvar_shard0_307.pt               (10 datasamples)

 78%|███████▊  | 233/300 [03:19<00:55,  1.20it/s]

  ├── Loaded testvar_shard0_308.pt               (10 datasamples)

 78%|███████▊  | 234/300 [03:19<00:54,  1.21it/s]

  ├── Loaded testvar_shard0_309.pt               (10 datasamples)

 78%|███████▊  | 235/300 [03:20<00:47,  1.36it/s]

  ├── Loaded testvar_shard0_31.pt                (10 datasamples)

 79%|███████▊  | 236/300 [03:21<00:49,  1.29it/s]

  ├── Loaded testvar_shard0_310.pt               (10 datasamples)

 79%|███████▉  | 237/300 [03:22<00:51,  1.21it/s]

  ├── Loaded testvar_shard0_311.pt               (10 datasamples)

 79%|███████▉  | 238/300 [03:23<00:53,  1.17it/s]

  ├── Loaded testvar_shard0_312.pt               (10 datasamples)

 80%|███████▉  | 239/300 [03:23<00:45,  1.33it/s]

  ├── Loaded testvar_shard0_313.pt               (10 datasamples)

 80%|████████  | 240/300 [03:24<00:49,  1.21it/s]

  ├── Loaded testvar_shard0_314.pt               (10 datasamples)

 80%|████████  | 241/300 [03:25<00:56,  1.04it/s]

  ├── Loaded testvar_shard0_315.pt               (10 datasamples)

 81%|████████  | 242/300 [03:26<00:52,  1.10it/s]

  ├── Loaded testvar_shard0_316.pt               (10 datasamples)

 81%|████████  | 243/300 [03:28<00:59,  1.04s/it]

  ├── Loaded testvar_shard0_317.pt               (10 datasamples)

 81%|████████▏ | 244/300 [03:29<00:59,  1.06s/it]

  ├── Loaded testvar_shard0_318.pt               (10 datasamples)

 82%|████████▏ | 245/300 [03:30<01:07,  1.22s/it]

  ├── Loaded testvar_shard0_319.pt               (10 datasamples)

 82%|████████▏ | 246/300 [03:32<01:10,  1.30s/it]

  ├── Loaded testvar_shard0_32.pt                (10 datasamples)

 82%|████████▏ | 247/300 [03:33<01:11,  1.36s/it]

  ├── Loaded testvar_shard0_320.pt               (10 datasamples)

 83%|████████▎ | 248/300 [03:35<01:16,  1.47s/it]

  ├── Loaded testvar_shard0_321.pt               (10 datasamples)

 83%|████████▎ | 249/300 [03:36<01:12,  1.42s/it]

  ├── Loaded testvar_shard0_322.pt               (10 datasamples)

 83%|████████▎ | 250/300 [03:37<01:01,  1.23s/it]

  ├── Loaded testvar_shard0_323.pt               (10 datasamples)

 84%|████████▎ | 251/300 [03:38<01:03,  1.29s/it]

  ├── Loaded testvar_shard0_324.pt               (10 datasamples)

 84%|████████▍ | 252/300 [03:40<01:06,  1.39s/it]

  ├── Loaded testvar_shard0_325.pt               (10 datasamples)

 84%|████████▍ | 253/300 [03:42<01:06,  1.41s/it]

  ├── Loaded testvar_shard0_326.pt               (10 datasamples)

 85%|████████▍ | 254/300 [03:43<00:59,  1.29s/it]

  ├── Loaded testvar_shard0_327.pt               (10 datasamples)

 85%|████████▌ | 255/300 [03:44<01:03,  1.40s/it]

  ├── Loaded testvar_shard0_328.pt               (10 datasamples)

 85%|████████▌ | 256/300 [03:46<01:03,  1.43s/it]

  ├── Loaded testvar_shard0_329.pt               (10 datasamples)

 86%|████████▌ | 257/300 [03:47<01:04,  1.51s/it]

  ├── Loaded testvar_shard0_33.pt                (10 datasamples)

 86%|████████▌ | 258/300 [03:48<00:52,  1.24s/it]

  ├── Loaded testvar_shard0_330.pt               (10 datasamples)

 86%|████████▋ | 259/300 [03:49<00:47,  1.16s/it]

  ├── Loaded testvar_shard0_331.pt               (10 datasamples)

 87%|████████▋ | 260/300 [03:51<00:51,  1.30s/it]

  ├── Loaded testvar_shard0_332.pt               (10 datasamples)

 87%|████████▋ | 261/300 [03:52<00:52,  1.35s/it]

  ├── Loaded testvar_shard0_333.pt               (10 datasamples)

 87%|████████▋ | 262/300 [03:54<00:54,  1.43s/it]

  ├── Loaded testvar_shard0_334.pt               (10 datasamples)

 88%|████████▊ | 263/300 [03:55<00:54,  1.47s/it]

  ├── Loaded testvar_shard0_335.pt               (10 datasamples)

 88%|████████▊ | 264/300 [03:56<00:47,  1.31s/it]

  ├── Loaded testvar_shard0_336.pt               (10 datasamples)

 88%|████████▊ | 265/300 [03:57<00:42,  1.21s/it]

  ├── Loaded testvar_shard0_337.pt               (10 datasamples)

 89%|████████▊ | 266/300 [03:58<00:37,  1.10s/it]

  ├── Loaded testvar_shard0_338.pt               (10 datasamples)

 89%|████████▉ | 267/300 [03:59<00:38,  1.17s/it]

  ├── Loaded testvar_shard0_339.pt               (10 datasamples)

 89%|████████▉ | 268/300 [04:01<00:40,  1.28s/it]

  ├── Loaded testvar_shard0_34.pt                (10 datasamples)

 90%|████████▉ | 269/300 [04:02<00:41,  1.32s/it]

  ├── Loaded testvar_shard0_340.pt               (10 datasamples)

 90%|█████████ | 270/300 [04:04<00:40,  1.35s/it]

  ├── Loaded testvar_shard0_341.pt               (10 datasamples)

 90%|█████████ | 271/300 [04:05<00:34,  1.19s/it]

  ├── Loaded testvar_shard0_342.pt               (10 datasamples)

 91%|█████████ | 272/300 [04:05<00:30,  1.09s/it]

  ├── Loaded testvar_shard0_343.pt               (10 datasamples)

 91%|█████████ | 273/300 [04:06<00:27,  1.03s/it]

  ├── Loaded testvar_shard0_344.pt               (10 datasamples)

 91%|█████████▏| 274/300 [04:07<00:25,  1.01it/s]

  ├── Loaded testvar_shard0_345.pt               (10 datasamples)

 92%|█████████▏| 275/300 [04:08<00:21,  1.16it/s]

  ├── Loaded testvar_shard0_346.pt               (10 datasamples)

 92%|█████████▏| 276/300 [04:09<00:23,  1.02it/s]

  ├── Loaded testvar_shard0_347.pt               (10 datasamples)

 92%|█████████▏| 277/300 [04:10<00:25,  1.10s/it]

  ├── Loaded testvar_shard0_348.pt               (10 datasamples)

 93%|█████████▎| 278/300 [04:12<00:25,  1.16s/it]

  ├── Loaded testvar_shard0_349.pt               (10 datasamples)

 93%|█████████▎| 279/300 [04:13<00:28,  1.35s/it]

  ├── Loaded testvar_shard0_35.pt                (10 datasamples)

 93%|█████████▎| 280/300 [04:14<00:23,  1.19s/it]

  ├── Loaded testvar_shard0_350.pt               (10 datasamples)

 94%|█████████▎| 281/300 [04:16<00:23,  1.25s/it]

  ├── Loaded testvar_shard0_351.pt               (10 datasamples)

 94%|█████████▍| 282/300 [04:17<00:22,  1.23s/it]

  ├── Loaded testvar_shard0_352.pt               (10 datasamples)

 94%|█████████▍| 283/300 [04:18<00:21,  1.25s/it]

  ├── Loaded testvar_shard0_353.pt               (10 datasamples)

 95%|█████████▍| 284/300 [04:20<00:20,  1.28s/it]

  ├── Loaded testvar_shard0_354.pt               (10 datasamples)

 95%|█████████▌| 285/300 [04:21<00:19,  1.27s/it]

  ├── Loaded testvar_shard0_355.pt               (10 datasamples)

 95%|█████████▌| 286/300 [04:22<00:16,  1.20s/it]

  ├── Loaded testvar_shard0_356.pt               (10 datasamples)

 96%|█████████▌| 287/300 [04:23<00:14,  1.08s/it]

  ├── Loaded testvar_shard0_357.pt               (10 datasamples)

 96%|█████████▌| 288/300 [04:24<00:13,  1.12s/it]

  ├── Loaded testvar_shard0_358.pt               (10 datasamples)

 96%|█████████▋| 289/300 [04:25<00:12,  1.14s/it]

  ├── Loaded testvar_shard0_359.pt               (10 datasamples)

 97%|█████████▋| 290/300 [04:26<00:12,  1.22s/it]

  ├── Loaded testvar_shard0_36.pt                (10 datasamples)

 97%|█████████▋| 291/300 [04:28<00:10,  1.20s/it]

  ├── Loaded testvar_shard0_360.pt               (10 datasamples)

 97%|█████████▋| 292/300 [04:29<00:09,  1.21s/it]

  ├── Loaded testvar_shard0_361.pt               (10 datasamples)

 98%|█████████▊| 293/300 [04:30<00:08,  1.17s/it]

  ├── Loaded testvar_shard0_362.pt               (10 datasamples)

 98%|█████████▊| 294/300 [04:31<00:06,  1.14s/it]

  ├── Loaded testvar_shard0_363.pt               (10 datasamples)

 98%|█████████▊| 295/300 [04:32<00:05,  1.12s/it]

  ├── Loaded testvar_shard0_364.pt               (10 datasamples)

 99%|█████████▊| 296/300 [04:33<00:04,  1.11s/it]

  ├── Loaded testvar_shard0_365.pt               (10 datasamples)

 99%|█████████▉| 297/300 [04:34<00:03,  1.12s/it]

  ├── Loaded testvar_shard0_366.pt               (10 datasamples)

 99%|█████████▉| 298/300 [04:35<00:02,  1.10s/it]

  ├── Loaded testvar_shard0_367.pt               (10 datasamples)

100%|█████████▉| 299/300 [04:36<00:01,  1.11s/it]

  ├── Loaded testvar_shard0_368.pt               (10 datasamples)

100%|██████████| 300/300 [04:37<00:00,  1.08it/s]

                                  auc_var  shd_var
LCM_CI_plain_100k_2c5M_20E_01_27   0.0012   5.7100
LCM_CI_perm_100k_2c5M_20E_01_28    0.0020   5.3927
LCM_CI_perm_100k_2c5M_20E_01_31    0.0041   5.9212
LCM_CI_perm_400k_2c5M_3E_01_29     0.0048   9.2913

In [ ]:
tvd

                                  auc_var  shd_var
LCM_CI_plain_100k_2c5M_20E_01_27   0.0012   5.7100
LCM_CI_perm_100k_2c5M_20E_01_28    0.0020   5.3927
LCM_CI_perm_100k_2c5M_20E_01_31    0.0041   5.9212
LCM_CI_perm_400k_2c5M_3E_01_29     0.0048   9.2913

: